name: Terraform Plan/Apply

on:
  workflow_dispatch: # 手動でのみ実行
    inputs:
      directory: # 実行したいディレクトリを指定
        description: 'Terraform directory to target (e.g., envs/dev)'
        required: true
        default: 'envs/dev'
      execute_apply: # applyの実行を選択する入力
        description: 'Set to true to execute terraform apply'
        required: false
        default: 'false'

jobs:
  terraform-plan:
    name: Terraform Plan or Apply
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    defaults:
      run:
        working-directory: ${{ github.event.inputs.directory }}
    steps:
      # リポジトリをチェックアウト
      - name: Checkout
        uses: actions/checkout@v4

      # ディレクトリの存在確認
      - name: Validate Directory Exists
        run: |
          echo "Checking directory: ${{ github.event.inputs.directory }}"
          if [ ! -d "${{ github.event.inputs.directory }}" ]; then
            echo "Error: Directory does not exist: ${{ github.event.inputs.directory }}"
            exit 1
          fi

      # Terraformファイルの存在確認
      - name: Check for Terraform Files
        run: |
          if [ -z "$(find ${{ github.event.inputs.directory }} -name '*.tf')" ]; then
            echo "Error: No Terraform files found in the directory: ${{ github.event.inputs.directory }}"
            exit 1
          fi

      # Terraformのセットアップ
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      # AWS認証情報のセットアップ
      - name: Setup AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ap-northeast-1
          role-to-assume: ${{ secrets.AWS_IAM_ROLE_TO_ASSUME }}
          role-session-name: GitHubActions
          role-duration-seconds: 3600

      # Terraformコードのフォーマットチェック
      - name: Terraform Format Check
        run: terraform fmt -check
        continue-on-error: false

      # Terraformの初期化
      - name: Terraform Init
        run: terraform init

      # Terraformバージョンの確認
      - name: Check Terraform Version
        run: terraform --version

      # Terraform Planの実行
      - name: Terraform Plan
        id: plan
        run: terraform plan -no-color
        continue-on-error: false

      # Terraform Applyの実行 (条件付き)
      - name: Terraform Apply
        id: apply
        if: ${{ github.event.inputs.execute_apply == 'true' }} # applyが選択された場合のみ実行
        run: terraform apply -auto-approve